export const THEME = {
  CHANGE_THEME: 'CHANGE_THEME',
  SET_THEME: 'SET_THEME',
  SET_DEFAULT_THEME: 'SET_DEFAULT_THEME',
};

export const AUTH = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  USER_DATA: 'USER_DATA',
  AUTH_TOKEN:'AUTH_TOKEN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SET_SIGN_UP_DATA: 'SET_SIGN_UP_DATA',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  RESET_AUTH: 'RESET_AUTH',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_EMAIL_STATUS: 'VERIFY_EMAIL_STATUS',
  RESET_VERIFY_EMAIL_STATUS: 'RESET_VERIFY_EMAIL_STATUS',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',
  RESET_FORGOT_PASSWORD: 'RESET_FORGOT_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
  USER_TOKEN: 'USER_TOKEN',
};

export const PREFERENCES = {
  SET_PREFERENCES: 'SET_PREFERENCES',
  SET_PREFERENCES_SUCCESS: 'SET_PREFERENCES_SUCCESS',
  SET_PREFERENCES_ERROR: 'SET_PREFERENCES_ERROR',
  SET_BIRTH_CONTROL_PREFERENCES: 'SET_BIRTH_CONTROL_PREFERENCES',
  RESET_BIRTH_CONTROL_PREFERENCES: 'RESET_BIRTH_CONTROL_PREFERENCES',
  SAVE_PREFERENCES: 'SAVE_PREFERENCES',
};

export const DASHBOARD = {
  GET_MY_JOURNAL: 'GET_MY_JOURNAL',
  GET_MY_JOURNAL_SUCCESS: 'GET_MY_JOURNAL_SUCCESS',
  GET_MY_JOURNAL_ERROR: 'GET_MY_JOURNAL_ERROR',

  GET_ALL_ARTICLE: 'GET_ALL_ARTICLE',
  GET_ALL_ARTICLE_SUCCESS: 'GET_ALL_ARTICLE_SUCCESS',
  GET_ALL_ARTICLE_ERROR: 'GET_ALL_ARTICLE_ERROR',

  GET_ALL_FORUM: 'GET_ALL_FORUM',
  GET_ALL_FORUM_SUCCESS: 'GET_ALL_FORUM_SUCCESS',
  GET_ALL_FORUM_ERROR: 'GET_ALL_FORUM_ERROR',
};

export const CALENDAR = {
  CREATE_JOURNAL_ENTRY: 'CREATE_JOURNAL_ENTRY',
  CREATE_JOURNAL_ENTRY_SUCCESS: 'CREATE_JOURNAL_ENTRY_SUCCESS',
  CREATE_JOURNAL_ENTRY_ERROR: 'CREATE_JOURNAL_ENTRY_ERROR',
  GET_JOURNAL_ENTRY: 'GET_JOURNAL_ENTRY',
  GET_JOURNAL_ENTRY_SUCCESS: 'GET_JOURNAL_ENTRY_SUCCESS',
  GET_JOURNAL_ENTRY_ERROR: 'GET_JOURNAL_ENTRY_ERROR',
  GET_PROBLEM_LIST: 'GET_PROBLEM_LIST',
  GET_PROBLEM_LIST_SUCCESS: 'GET_PROBLEM_LIST_SUCCESS',
  GET_PROBLEM_LIST_ERROR: 'GET_PROBLEM_LIST_ERROR',
  GET_PROBLEMS_FOR_DATE: 'GET_PROBLEMS_FOR_DATE',
  GET_PROBLEMS_FOR_DATE_SUCCESS: 'GET_PROBLEMS_FOR_DATE_SUCCESS',
  GET_PROBLEMS_FOR_DATE_ERROR: 'GET_PROBLEMS_FOR_DATE_ERROR',
};
